[tool.ruff]
# linting ruleset
select = ["E", "F", "W", "C90", "I"]
# ignored rules
ignore = ["C901"]       # example: disable complexity checks
                        # this project has a lot of UI if-else checks
                        # thus using arbitrary complexity limits are not useful
# Maximum line length
line-length = 88
# Enable automatic fixes for compatible rules
fix = true
